@startuml plantuml_simple.png

namespace Wolio {

  namespace Wolio.Actor.Player {
    PlayerState o-- PlayerConfig

    class PlayerState {
      +Transform GroundCheck
      +Transform CeilingCheck
      -PlayerConfig PlayerConfig
      -SpriteRenderer SpriteRenderer
      -Rigidbody2D Rigidbody2D
      -Animator Animator
      +IntReactiveProperty Hp
      +ReactiveProperty<bool> IsDead
      +ReactiveProperty<bool> IsGrounded
      +ReactiveProperty<bool> IsDashing
      +ReactiveProperty<bool> IsRunning
      +ReactiveProperty<bool> IsJumping
      +ReactiveProperty<bool> IsStanding
      +ReactiveProperty<bool> IsCrouching
      +ReactiveProperty<bool> IsCreeping
      +ReactiveProperty<bool> IsTouchingWall
      +ReactiveProperty<bool> IsClimbing
      +ReactiveProperty<bool> IsClimbable
      +ReactiveProperty<bool> IsStandingLightAttack
      +ReactiveProperty<bool> IsStandingMiddleAttack
      +ReactiveProperty<bool> IsStandingHighAttack
      +ReactiveProperty<bool> IsCrouchingLightAttack
      +ReactiveProperty<bool> IsCrouchingMiddleAttack
      +ReactiveProperty<bool> IsCrouchingHighAttack
      +ReactiveProperty<bool> IsJumpingLightAttack
      +ReactiveProperty<bool> IsJumpingMiddleAttack
      +ReactiveProperty<bool> IsJumpingHighAttack
      +ReactiveProperty<bool> IsStandingGuard
      +ReactiveProperty<bool> IsCrouchingGuard
      +ReactiveProperty<bool> IsJumpingGuard
      +ReactiveProperty<bool> IsStandingDamage
      +ReactiveProperty<bool> IsCrouchingDamage
      +ReactiveProperty<bool> IsJumpingDamage
      +ReactiveProperty<bool> IsStandingHitBack
      +ReactiveProperty<bool> IsCrouchingHitBack
      +ReactiveProperty<bool> IsJumpingHitBack
      +ReactiveProperty<bool> IsStandingGuardBack
      +ReactiveProperty<bool> IsCrouchingGuardBack
      +ReactiveProperty<bool> IsJumpingGuardBack
      +ReactiveProperty<bool> FacingRight
      -void Awake()
      -void Start()
    }

    class PlayerConfig {
      +float MaxSpeed = 10f
      +float KnockBackSpeed = 3f
      +float DashSpeed = 10f
      +float CreepSpeed = 4f
      +float JumpForce = 400f
      +bool AirControl = false
      +LayerMask WhatIsGround
      +int shotwait = 0
      -const float k_GroundedRadius = .2f
      +float GravityScaleStore = 5f
      +const float FallVelocityLimit = -6f
      +int StandingLightAttackStartup
      +int StandingLightAttackActive
      +int StandingLightAttackRecovery
      -void Start()
    }

    class Key {
      +ReactiveProperty<float> Horizontal
      +ReactiveProperty<float> Vertical
      +bool A
      +bool S
      +bool D
      +bool Z
      +bool X
      +bool C
      +bool LeftShift
      +bool Space
      +ReactiveProperty<bool> IsAvailable
      -void Awake()
      -void Start()
      -void UpdateAsObservables()
    }

    namespace Wolio.Actor.Player.Basics{
      PlayerTurn o-- Wolio.Actor.Player.PlayerState
      PlayerTurn o-- Wolio.Actor.Player.Key

      class PlayerTurn {
        -GameObject Player
        -Key Key
        -PlayerState PlayerState
        -SpriteRenderer SpriteRenderer
        -BoxCollider2D[] BoxColliders2D
        -CircleCollider2D[] CircleColliders2D
        -void Awake()
        -void Start()
        -void Turn()
      }

      PlayerStand o-- Wolio.Actor.Player.PlayerState
      PlayerStand o-- Wolio.Actor.Player.Key

      class PlayerStand {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -CircleCollider2D CircleCollider2D
        -void Awake()
        -void Start()
      }

      PlayerRun o-- Wolio.Actor.Player.PlayerState
      PlayerRun o-- Wolio.Actor.Player.Key

      class PlayerRun {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -CircleCollider2D CircleCollider2D
        -float MaxSpeed
        -void Awake()
        -void Start()
        -void Run()
      }

      PlayerJump o-- Wolio.Actor.Player.PlayerState
      PlayerJump o-- Wolio.Actor.Player.Key

      class PlayerJump {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -float JumpForce
        -void Awake()
        -void Start()
      }

      PlayerCrouch o-- Wolio.Actor.Player.PlayerState
      PlayerCrouch o-- Wolio.Actor.Player.Key

      class PlayerCrouch {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -GameObject CeilingCheck
        -LayerMask WhatIsGround
        -void Awake()
        -void Start()
      }

      PlayerCreep o-- Wolio.Actor.Player.PlayerState
      PlayerCreep o-- Wolio.Actor.Player.Key

      class PlayerCreep {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -float CreepSpeed
        -void Awake()
        -void Start()
        -void Creep()
      }

      PlayerAirMove o-- Wolio.Actor.Player.PlayerState
      PlayerAirMove o-- Wolio.Actor.Player.Key

      class PlayerAirMove {
        -PlayerState PlayerState
        -Key Key
        -Rigidbody2D Rigidbody2D
        -void Awake()
        -void Start()
        -void AirMove()
      }

      PlayerWallKickJump o-- Wolio.Actor.Player.PlayerState
      PlayerWallKickJump o-- Wolio.Actor.Player.Key

      class PlayerWallKickJump {
        -GameObject Player
        -PlayerState PlayerState
        -Key Key
        -Rigidbody2D Rigidbody2D
        -SpriteRenderer SpriteRenderer
        -BoxCollider2D[] BoxColliders2D
        -CircleCollider2D[] CircleColliders2D
        -void Awake()
        -void Start()
        -void WallKickJump()
      }
    }

    namespace Wolio.Actor.Player.Attacks.NormalAttacks.StandingAttacks {
      PlayerStandingLightAttack o-- Wolio.Actor.Player.PlayerState
      PlayerStandingLightAttack o-- Wolio.Actor.Player.Key

      class PlayerStandingLightAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -CircleCollider2D CircleCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -int Recovery
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }

      PlayerStandingMiddleAttack o-- Wolio.Actor.Player.PlayerState
      PlayerStandingMiddleAttack o-- Wolio.Actor.Player.Key

      class PlayerStandingMiddleAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -CircleCollider2D CircleCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -int Recovery
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }

      PlayerStandingHighAttack o-- Wolio.Actor.Player.PlayerState
      PlayerStandingHighAttack o-- Wolio.Actor.Player.Key

      class PlayerStandingHighAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -CircleCollider2D CircleCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -int Recovery
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }
    }

    namespace Wolio.Actor.Player.Attacks.NormalAttacks.CrouchingAttacks {
      PlayerCrouchingLightAttack o-- Wolio.Actor.Player.PlayerState
      PlayerCrouchingLightAttack o-- Wolio.Actor.Player.Key

      class PlayerCrouchingLightAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -int Recovery
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }

      PlayerCrouchingMiddleAttack o-- Wolio.Actor.Player.PlayerState
      PlayerCrouchingMiddleAttack o-- Wolio.Actor.Player.Key

      class PlayerCrouchingMiddleAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -int Recovery
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }

      PlayerCrouchingHighAttack o-- Wolio.Actor.Player.PlayerState
      PlayerCrouchingHighAttack o-- Wolio.Actor.Player.Key

      class PlayerCrouchingHighAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -int Recovery
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }
    }

    namespace Wolio.Actor.Player.Attacks.NormalAttacks.JumpingAttacks {
      PlayerJumpingLightAttack o-- Wolio.Actor.Player.PlayerState
      PlayerJumpingLightAttack o-- Wolio.Actor.Player.Key

      class PlayerJumpingLightAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }

      PlayerJumpingMiddleAttack o-- Wolio.Actor.Player.PlayerState
      PlayerJumpingMiddleAttack o-- Wolio.Actor.Player.Key

      class PlayerJumpingMiddleAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }

      PlayerJumpingHighAttack o-- Wolio.Actor.Player.PlayerState
      PlayerJumpingHighAttack o-- Wolio.Actor.Player.Key

      class PlayerJumpingHighAttack {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HitBox
        -BoxCollider2D HurtBox
        -int Startup
        -int Active
        -void Awake()
        -void Start()
        +IEnumerator Attack()
      }
    }

    namespace Wolio.Actor.Player.Guards {
      PlayerStandingGuard o-- Wolio.Actor.Player.PlayerState
      PlayerStandingGuard o-- Wolio.Actor.Player.Key

      class PlayerStandingGuard {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -CircleCollider2D CircleCollider2D
        -BoxCollider2D HurtBox
        -void Awake()
        -void Start()
        +IEnumerator StandingGuard()
      }

      PlayerCrouchingGuard o-- Wolio.Actor.Player.PlayerState
      PlayerCrouchingGuard o-- Wolio.Actor.Player.Key

      class PlayerCrouchingGuard {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -void Awake()
        -void Start()
        +IEnumerator CrouchingGuard()
      }

      PlayerJumpingGuard o-- Wolio.Actor.Player.PlayerState
      PlayerJumpingGuard o-- Wolio.Actor.Player.Key

      class PlayerJumpingGuard {
        -Animator Animator
        -ObservableStateMachineTrigger ObservableStateMachineTrigger
        -PlayerState PlayerState
        -Rigidbody2D PlayerRigidbody2D
        -Key Key
        -BoxCollider2D BoxCollider2D
        -BoxCollider2D HurtBox
        -void Awake()
        -void Start()
        +IEnumerator JumpingGuard()
      }
    }

    namespace Wolio.Actor.Player.KnockBacks.GuardBacks {
      PlayerStandingGuardBack o-- Wolio.Actor.Player.PlayerState
      PlayerStandingGuardBack o-- Wolio.Actor.Player.Key

      class PlayerStandingGuardBack {
        -PlayerState PlayerState
        -Rigidbody2D Rigidbody2D
        -BoxCollider2D BoxCollider2D
        -void Awake()
        -void Start()
        +IEnumerator StandingGuardBack()
      }

      PlayerCrouchingGuardBack o-- Wolio.Actor.Player.PlayerState
      PlayerCrouchingGuardBack o-- Wolio.Actor.Player.Key

      class PlayerCrouchingGuardBack {
        -PlayerState PlayerState
        -Rigidbody2D Rigidbody2D
        -BoxCollider2D BoxCollider2D
        -void Awake()
        -void Start()
        +IEnumerator CrouchingGuardBack()
      }

      PlayerJumpingGuardBack o-- Wolio.Actor.Player.PlayerState
      PlayerJumpingGuardBack o-- Wolio.Actor.Player.Key

      class PlayerJumpingGuardBack {
        -PlayerState PlayerState
        -Rigidbody2D Rigidbody2D
        -BoxCollider2D BoxCollider2D
        -void Awake()
        -void Start()
        +IEnumerator JumpingGuardBack()
      }
    }

    namespace Wolio.Actor.Player.KnockBacks.HitBacks{
      PlayerStandingHitBack o-- Wolio.Actor.Player.PlayerState

      class PlayerStandingHitBack {
        -PlayerState PlayerState
        -Rigidbody2D Rigidbody2D
        -BoxCollider2D BoxCollider2D
        -void Awake()
        -void Start()
        -IEnumerator StandingHitBack()
      }
    }
  }
}

@enduml
